exception for "terminating connection due to administrator command"
this would bix a bug - when app hits max connections limit in pg db the whole app crashes with:

events.js:72
        throw er; // Unhandled 'error' event
              ^
error: terminating connection due to administrator command

code is borrowed from https://github.com/sequelize/sequelize/issues/1854